config/routes.rb
Rails.application.routes.draw do

  get 'broadcast/index'
  post 'broadcast/send_broadcast'

  get 'dashboard/index'

  post 'messages/create'

  resources :checkpoints do
    collection do
      post 'sort'
    end
  end

  resources :teams do
    member do
      post 'start'
      post 'reset'
    end
  end

  root 'dashboard#index'

end

app/models/checkpoint.rb
class Checkpoint < ActiveRecord::Base

  before_validation :get_next_order, :on => :create

  has_many :logs

  validates :message, presence: true, uniqueness: true
  validates :response, presence: true
  validates :points, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :order, numericality: { only_integer: true, greater_than: 0 }

  def success_message
    if self.success.blank?
      self.response
    else
      "#{self.success} #{self.response}"
    end
  end

  private

  def get_next_order
    self.order = Checkpoint.count + 1
  end

end

app/models/log.rb
class Log < ActiveRecord::Base

  belongs_to :checkpoint
  belongs_to :team
  belongs_to :person

end

app/models/person.rb
class Person < ActiveRecord::Base

  belongs_to :team
  has_many :logs

  validates :number, presence: true, uniqueness: true, format: /\A\+[0-9]{11}\z/

  def description
    if self.name.blank?
      self.number
    else
      self.name
    end
  end

end

app/models/team.rb
class Team < ActiveRecord::Base

  has_many :logs
  has_many :people

  validates :code, presence: true, uniqueness: true
  validates :name, presence: true
  validates :position, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  accepts_nested_attributes_for :people

  def started?
    self.position != 0
  end

  def start!
    unless started?
      self.update_attribute :position, 1
    end
  end

  def reset!
    self.update_attribute :position, 0
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/broadcast_controller.rb
class BroadcastController < SecuredController

  def index
    @teams = Team.order :name
  end

  def send_broadcast
    # Ensure there's a message
    if params[:message].blank?
      redirect_to broadcast_index_path, :notice => 'A message is required'
      return
    end

    # Get the people
    if params[:id] == 'all'
      people = Person.all
    else
      people = Person.where(team_id: params[:id])
    end

    # Send the message
    client = Twilio::REST::Client.new APP_CONFIG['twilio_account_sid'], APP_CONFIG['twilio_account_token']
    people.each do |person|
      client.account.messages.create(from: APP_CONFIG['twilio_number'], to: person.number, body: params[:message])
    end

    redirect_to broadcast_index_path, :notice => 'You message was sent'
  end


end

app/controllers/checkpoints_controller.rb
class CheckpointsController < SecuredController

  def create
    @checkpoint = Checkpoint.new checkpoint_params

    if @checkpoint.save
      redirect_to checkpoints_path, notice: 'The checkpoint was created successfully.'
    else
      render 'new'
    end
  end

  def index
    @checkpoints = Checkpoint.order(:order)
  end

  def new
    @checkpoint = Checkpoint.new
  end

  def show
    @checkpoint = Checkpoint.find params[:id]
  end

  def sort
    order = 1
    params[:order].each do |id|
      checkpoint = Checkpoint.find id
      checkpoint.update_attribute :order, order
      order += 1
    end

    respond_to do |format|
      format.json { head :ok }
    end
  end

  def update
    @checkpoint = Checkpoint.find params[:id]
    @checkpoint.update_attributes checkpoint_params

    if @checkpoint.save
      redirect_to checkpoints_path, notice: 'The checkpoint was updated successfully.'
    else
      render 'show'
    end
  end

  private

  def checkpoint_params
    params.require(:checkpoint).permit(:message, :success, :response, :points)
  end

end

app/controllers/concerns/webhookable.rb
module Webhookable
  extend ActiveSupport::Concern

  def set_header
    response.headers["Content-Type"] = "text/xml"
  end

  def render_twiml(response)
    render text: response.text
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < SecuredController

  def index
    @teams = Team.order :name
  end

end

app/controllers/messages_controller.rb
require 'twilio-ruby'

class MessagesController < ApplicationController
  include Webhookable

  after_filter :set_header, only: :create
  skip_before_action :verify_authenticity_token, only: :create

  def create
    # Extract the body
    body = params['Body'].strip.downcase

    if body =~ /team ([a-z0-9]+)/
      response = process_team($1)
    else
      # Ensure the user is authorized
      person = Person.find_by number: params['From']

      if person.nil?
        response = makeResponse 'You must be registered to answer questions.'
      elsif !person.team.started?
        response = makeResponse 'Your team has not been started. Contact the administrator for help.'
      else
        if body == '?'
          response = process_help(body, person)
        else
          response = process_checkpoint(body, person)
        end
      end
    end

    render_twiml response
  end

  private

  def makeResponse(message)
    return Twilio::TwiML::Response.new do |r|
      r.Message message
    end
  end

  def process_help(body, person)
    # Get the team position
    position = person.team.position

    # Get the current checkpoint
    checkpoint = Checkpoint.find_by order: position

    # Send back the response
    makeResponse checkpoint.response
  end

  def process_checkpoint(body, person)
    # Get the team position
    position = person.team.position

    # Get the next checkpoint
    checkpoint = Checkpoint.find_by order: position + 1

    # The end?
    if checkpoint.nil?
      return makeResponse "You're already done. Congratulations. Again."
    end

    # Did it match?
    if /#{checkpoint.message}/ =~ body
      # Move to the next position
      person.team.update_attribute :position, checkpoint.order

      # Log it
      log = Log.new
      log.checkpoint = checkpoint
      log.person = person
      log.team = person.team
      log.save

      return makeResponse checkpoint.success_message
    else
      return makeResponse 'Nope.'
    end
  end

  def process_team(code)
    # Look for an existing user
    person = Person.find_by number: params['From']
    if !person.nil?
      return makeResponse 'This number is already associated with a team. Contact the administrator for help.'
    end

    # Look for the team
    team = Team.where('lower(code) = ?', code).first
    if team.nil?
      return makeResponse 'Could not find the team. Please try again.'
    end

    # Create the person
    person = team.people.build number: params['From']
    if person.save
      return makeResponse "You have been registered on Team #{team.name}."
    else
      return makeResponse 'An error occurred during registration. Contact the administrator for help.'
    end
  end

end

app/controllers/secured_controller.rb
class SecuredController < ApplicationController
  http_basic_authenticate_with :name => APP_CONFIG['username'], :password => APP_CONFIG['password']
end

app/controllers/teams_controller.rb
class TeamsController < SecuredController

  def create
    @team = Team.new team_params

    if @team.save
      redirect_to team_path(@team), notice: 'This team was created successfully.'
    else
      render 'new'
    end
  end

  def index
    @teams = Team.order :name
  end

  def new
    @team = Team.new
  end

  def reset
    @team = Team.find params[:id]
    @team.reset!

    redirect_to teams_path
  end

  def show
    @team = Team.find params[:id]
  end

  def start
    @team = Team.find params[:id]
    @team.start!

    redirect_to teams_path
  end

  def update
    @team = Team.find params[:id]
    @team.update_attributes team_params

    if @team.save
      redirect_to team_path(@team), notice: 'This team was updated successfully.'
    else
      render 'show'
    end
  end

  private

  def team_params
    params.require(:team).permit(:code, :name, people_attributes: [ :id, :name ])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for :title, page_title.to_s
  end

end

app/helpers/broadcast_helper.rb
module BroadcastHelper
end

app/helpers/checkpoints_helper.rb
module CheckpointsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/broadcast/index.html.erb
<% title 'Broadcast' %>

<%= form_tag broadcast_send_broadcast_path, method: 'post' do %>
  <%= label_tag :id, 'Team' %>
  <%= select_tag :id, options_for_select([[ 'All', 'all' ]] + @teams.map { |team| [ team.name, team.id ] }) %>
  <%= label_tag :message, 'Message' %>
  <%= text_area_tag :message %>
  <%= submit_tag 'Send Broadcast' %>
<% end %>

app/views/checkpoints/index.html.erb
<% title 'Checkpoints' %>

<% if @checkpoints.empty? %>
  <div class="flash-info">
    <span>There are no checkpoints, yet.</span>
  </div>
<% end %>

<div id="checkpoints" class="sortable" data-url="<%= sort_checkpoints_url %>">
  <% @checkpoints.each do |checkpoint| %>
    <div class="checkpoint item" id="checkpoint-<%= checkpoint.id %>" data-item-id="<%= checkpoint.id %>">
      <div class="message">
        <%= link_to checkpoint.message, checkpoint_path(checkpoint) %>
      </div>

      <% if checkpoint.points > 0 %>
        <div class="points">
          <%= pluralize(checkpoint.points, 'points') %>
        </div>
      <% end %>

      <p>
        <% unless checkpoint.success.empty? %>
          <span class="success"><%= checkpoint.success %></span>
        <% end %>
        <span class="response"><%= checkpoint.response %></span>
      </p>
    </div>
  <% end %>
</div>

<%= link_to 'Create a checkpoint', new_checkpoint_path, :class => 'button' %>
<button class="toggle-sort" data-state="disabled">Sort</button>

app/views/checkpoints/new.html.erb
<% title 'Create A New Checkpoint' %>

<%= form_for(@checkpoint) do |f| %>
  <% if @checkpoint.errors.any? %>
    <div class="notice notice-error">
      <%= @checkpoint.errors.full_messages.join '. ' %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_field :message %>
  </div>

  <div class="field">
    <%= f.label :success %>
    <%= f.text_field :success %>
  </div>

  <div class="field">
    <%= f.label :response %>
    <%= f.text_field :response %>
  </div>

  <div class="field">
    <%= f.label :points %>
    <%= f.number_field :points, min: 0, step: 1 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkpoints/show.html.erb
<% title "Checkpoint #{@checkpoint.message}" %>

<%= form_for(@checkpoint) do |f| %>
  <% if @checkpoint.errors.any? %>
    <div class="notice notice-error">
      <%= @checkpoint.errors.full_messages.join '. ' %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_field :message %>
  </div>

  <div class="field">
    <%= f.label :success %>
    <%= f.text_field :success %>
  </div>

  <div class="field">
    <%= f.label :response %>
    <%= f.text_field :response %>
  </div>

  <div class="field">
    <%= f.label :points %>
    <%= f.number_field :points, min: 0, step: 1 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboard/index.html.erb
<% title 'Dashboard' %>

<section id="dashboard">
  <% @teams.each do |team| %>
    <div class="team">
      <h2><%= team.name %></h2>

      <table>
        <thead>
          <tr>
            <th>Message</th>
            <th>Who?</th>
            <th>When?</th>
            <th>Points</th>
          </tr>
        </thead>
        <tbody>
          <% count = 0 %>
          <% team.logs.order(created_at: :desc).each do |log| %>
            <tr>
              <td><%= log.checkpoint.message %></td>
              <td><%= log.person.description %></td>
              <td><%= log.created_at.to_formatted_s(:short) %></td>
              <td>
                <% if log.checkpoint.points > 0 %>
                  <%= log.checkpoint.points %>
                  <% count += log.checkpoint.points %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="3">Total Points:</td>
            <td><%= count %></td>
          </tr>
        </tfoot>
      </table>
    </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="navigation">
    <div class="navigation-wrapper">
      <a href="<%= root_path %>" class="logo">
        <%= image_tag 'bike.png' %>
      </a>
      <a href="" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
      <div class="nav">
        <ul id="navigation-menu">
          <li class="nav-link"><%= link_to 'Broadcast', broadcast_index_path %></li>
          <li class="nav-link"><%= link_to 'Dashboard', dashboard_index_path %></li>
          <li class="nav-link"><%= link_to 'Teams', teams_path %></li>
          <li class="nav-link"><%= link_to 'Checkpoints', checkpoints_path %></li>
        </ul>
      </div>
    </div>
  </header>


  <h1 id="title"><%= yield(:title) %></h1>

  <% flash.each do |name, message| %>
    <div class="flash-<%= name %>">
      <span><%= message %></span>
    </div>
  <% end %>

  <%= yield %>

</body>
</html>